AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  From Sample SAM Template

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HistoryNodejsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: history_nodejs/
      Handler: index.lambda_handler
      Runtime: nodejs8.10
      Events:
        HistoryNodejs:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /history
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HistoryNodejsApi:
    Description: "API Gateway endpoint URL for `prod` stage for HistoryNodejs function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/history/"
  HistoryNodejsFunction:
    Description: "HistoryNodejs Lambda Function ARN"
    Value: !GetAtt HistoryNodejsFunction.Arn
  HistoryNodejsFunctionIamRole:
    Description: "Implicit IAM Role created for HistoryNodejs function"
    Value: !GetAtt HistoryNodejsFunctionRole.Arn
